export const PROMPTS = [
    "What made you smile today, even just a little?",
    "What's one thing you're proud of this week?",
    "What do you need right now that you're not giving yourself?",
    "Describe your mood in 3 words.",
    "What's one small win you had today?",
    "What would make tomorrow just a bit better?",
    "Who or what gave you energy today?",
    "What's something you want to let go of today?",
    "If your feelings were a weather, what would the forecast be?",
    "What's one kind thing you can do for yourself tonight?",
    "What challenged you today, and how did you handle it?",
    "What are you grateful for, even in a hard day?",
    "Describe somewhere you feel completely safe and calm.",
    "What do you wish someone would say to you right now?",
    "What's been on your mind that you haven't said out loud?",
    "Name three things you can see, two you can hear, one you can feel.",
    "What boundaries do you need to set to protect your peace?",
    "How has your body been feeling today?",
    "What does rest look like for you?",
    "What small step can you take toward feeling better?",
];
